/* ============================================================
   Starword — lista de palabras de 5 letras (inglés)
   ------------------------------------------------------------
   - `answers`: palabras candidatas a ser la solución (diaria o
     práctica). Curadas para ser razonablemente comunes.
   - `allowed`: palabras adicionales válidas como intento, que no
     se usan como solución pero sí se aceptan al adivinar.
   El conjunto de validación de intentos = answers ∪ allowed.
   No hay módulos: se expone en `window.STARWORD`.
   ============================================================ */

const STARWORD_ANSWERS = [
  "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult", "after", "again",
  "agent", "agree", "ahead", "alarm", "album", "alert", "alike", "alive", "allow", "alone",
  "along", "alter", "among", "anger", "angle", "angry", "apart", "apple", "apply", "arena",
  "argue", "arise", "array", "aside", "asset", "audio", "audit", "avoid", "award", "aware",
  "badly", "baker", "bases", "basic", "beach", "began", "begin", "begun", "being", "below",
  "bench", "birth", "black", "blame", "blank", "blast", "blend", "blind", "block", "blood",
  "board", "boost", "booth", "bound", "brain", "brand", "brass", "brave", "bread", "break",
  "breed", "brief", "bring", "broad", "broke", "brown", "build", "built", "buyer", "cable",
  "carry", "catch", "cause", "chain", "chair", "chaos", "charm", "chart", "chase", "cheap",
  "check", "chest", "chief", "child", "chose", "civil", "claim", "class", "clean", "clear",
  "click", "climb", "clock", "close", "cloth", "cloud", "coach", "coast", "could", "count",
  "court", "cover", "craft", "crash", "crazy", "cream", "crime", "cross", "crowd", "crown",
  "crude", "curve", "cycle", "daily", "dance", "dated", "dealt", "death", "debut", "delay",
  "depth", "doing", "doubt", "dozen", "draft", "drama", "drank", "dream", "dress", "drill",
  "drink", "drive", "drove", "dying", "eager", "early", "earth", "eight", "elite", "empty",
  "enemy", "enjoy", "enter", "entry", "equal", "error", "event", "every", "exact", "exist",
  "extra", "faith", "false", "fault", "fiber", "field", "fifth", "fifty", "fight", "final",
  "first", "fixed", "flash", "fleet", "floor", "fluid", "focus", "force", "forth", "forty",
  "forum", "found", "frame", "frank", "fraud", "fresh", "front", "fruit", "fully", "funny",
  "giant", "given", "glass", "globe", "going", "grace", "grade", "grand", "grant", "grass",
  "great", "green", "gross", "group", "grown", "guard", "guess", "guest", "guide", "happy",
  "heart", "heavy", "horse", "hotel", "house", "human", "ideal", "image", "index", "inner",
  "input", "issue", "joint", "judge", "known", "label", "large", "laser", "later", "laugh",
  "layer", "learn", "lease", "least", "leave", "legal", "level", "light", "limit", "links",
  "lives", "local", "logic", "loose", "lower", "lucky", "lunch", "lying", "magic", "major",
  "maker", "march", "match", "maybe", "mayor", "meant", "media", "metal", "might", "minor",
  "minus", "mixed", "model", "money", "month", "moral", "motor", "mount", "mouse", "mouth",
  "movie", "music", "needs", "never", "newly", "night", "noise", "north", "noted", "novel",
  "nurse", "occur", "ocean", "offer", "often", "order", "other", "ought", "paint", "panel",
  "paper", "party", "peace", "phase", "phone", "photo", "piece", "pilot", "pitch", "place",
  "plain", "plane", "plant", "plate", "point", "pound", "power", "press", "price", "pride",
  "prime", "print", "prior", "prize", "proof", "proud", "prove", "queen", "quick", "quiet",
  "quite", "radio", "raise", "range", "rapid", "ratio", "reach", "ready", "refer", "right",
  "rival", "river", "rough", "round", "route", "royal", "rural", "scale", "scene", "scope",
  "score", "sense", "serve", "seven", "shall", "shape", "share", "sharp", "sheet", "shelf",
  "shell", "shift", "shirt", "shock", "shoot", "short", "shown", "sight", "since", "sixth",
  "sixty", "sized", "skill", "sleep", "slide", "small", "smart", "smile", "smoke", "solid",
  "solve", "sorry", "sound", "south", "space", "spare", "speak", "speed", "spend", "spent",
  "split", "spoke", "sport", "staff", "stage", "stake", "stand", "start", "state", "steam",
  "steel", "stick", "still", "stock", "stone", "stood", "store", "storm", "story", "strip",
  "stuck", "study", "stuff", "style", "sugar", "suite", "super", "sweet", "table", "taken",
  "taste", "taxes", "teach", "teeth", "thank", "theft", "their", "theme", "there", "these",
  "thick", "thing", "think", "third", "those", "three", "threw", "throw", "tight", "times",
  "tired", "title", "today", "topic", "total", "touch", "tough", "tower", "track", "trade",
  "train", "treat", "trend", "trial", "tribe", "trick", "tried", "tries", "truck", "truly",
  "trust", "truth", "twice", "under", "undue", "union", "unity", "until", "upper", "upset",
  "urban", "usage", "usual", "valid", "value", "video", "virus", "visit", "vital", "voice",
  "waste", "watch", "water", "wheel", "where", "which", "while", "white", "whole", "whose",
  "woman", "women", "world", "worry", "worse", "worst", "worth", "would", "wound", "write",
  "wrong", "wrote", "young", "youth"
];

const STARWORD_ALLOWED = [
  "adept", "adieu", "adore", "agile", "aisle", "amber", "ample", "ankle", "apron", "aroma",
  "arose", "ashen", "atlas", "attic", "azure", "bacon", "badge", "bagel", "baron", "basil",
  "batch", "beard", "beech", "beige", "belch", "belle", "berry", "bicep", "biome", "blaze",
  "bleak", "bleed", "bless", "blink", "bliss", "bloat", "bloke", "blond", "bloom", "blown",
  "bluff", "blunt", "blush", "brace", "braid", "brave", "bribe", "brine", "brink", "brisk",
  "broth", "bulky", "bunch", "burnt", "cabin", "cadet", "camel", "candy", "canoe", "caper",
  "cargo", "carve", "caste", "cedar", "chalk", "champ", "chant", "cheek", "cheer", "chess",
  "chili", "chime", "chirp", "choir", "chord", "chunk", "churn", "cider", "cigar", "civic",
  "clamp", "clash", "clasp", "cleat", "cleft", "clerk", "cliff", "cloak", "clone", "clout",
  "clump", "clung", "coral", "couch", "cough", "cramp", "crane", "crank", "crate", "crepe",
  "crisp", "croak", "crook", "crumb", "crust", "cubic", "dairy", "daisy", "dandy", "debit",
  "decal", "decay", "decor", "decoy", "delta", "demon", "denim", "depot", "derby", "deter",
  "devil", "diary", "dimly", "dingy", "ditch", "ditto", "diver", "dodge", "donor", "dough",
  "downy", "dowry", "drain", "drape", "drawn", "dread", "dwarf", "dwell", "eagle", "elbow",
  "elder", "elope", "elude", "ember", "ethic", "evoke", "exalt", "excel", "expel", "extol",
  "fable", "facet", "faint", "fairy", "fancy", "feign", "fence", "feral", "ferry", "fetch",
  "fever", "fewer", "fiend", "filet", "filth", "finch", "fjord", "flair", "flake", "flank",
  "flare", "flask", "fleck", "flesh", "flick", "fling", "flint", "flirt", "float", "flock",
  "flora", "flour", "flown", "flung", "flush", "foamy", "focal", "foray", "forge", "forgo",
  "foyer", "frail", "fried", "frill", "frock", "frost", "frown", "fudge", "gauge", "gaunt",
  "gauze", "gawky", "gecko", "genie", "genre", "ghoul", "girth", "glade", "gland", "glare",
  "gleam", "glean", "glide", "glint", "gloat", "gloom", "glory", "gloss", "glove", "glyph",
  "gnash", "gnome", "gorge", "gouge", "grail", "grape", "graph", "grasp", "grave", "gravy",
  "graze", "grime", "grind", "groan", "groin", "groom", "grope", "gruff", "grunt", "guild",
  "guile", "guilt", "gusto", "hatch", "haunt", "haven", "hazel", "hedge", "hefty", "heron",
  "hinge", "hippo", "hitch", "hoard", "hobby", "hoist", "honey", "hound", "hover", "humid",
  "humor", "hunch", "hurry", "husky", "hyena", "idiom", "igloo", "imbue", "inept", "infer",
  "ingot", "inlay", "irate", "irony", "ivory", "jaunt", "jelly", "jewel", "jiffy", "joker",
  "jolly", "joust", "juicy", "jumbo", "kayak", "khaki", "knack", "kneel", "knelt", "knife",
  "knock", "knoll", "koala", "lapel", "lapse", "larva", "latch", "lathe", "leaky", "leapt",
  "ledge", "leech", "lemon", "lemur", "liken", "lilac", "limbo", "liner", "lingo", "liver",
  "llama", "loath", "lobby", "lofty", "loser", "lotus", "lousy", "loyal", "lucid", "lunar",
  "lurch", "lurid", "lusty", "lymph", "lyric", "macho", "madly", "mango", "manor", "marsh",
  "mason", "mauve", "maxim", "meaty", "melon", "mercy", "merge", "merit", "merry", "motel",
  "motto", "mound", "mourn", "muddy", "mulch", "mummy", "mural", "murky", "mushy", "musty",
  "naive", "nanny", "nasal", "nasty", "naval", "nerdy", "niche", "niece", "ninja", "ninth",
  "noble", "nomad", "nudge", "octet", "olive", "onset", "optic", "orbit", "organ", "ovary",
  "ozone", "pagan", "panic", "parka", "pasta", "patio", "pause", "peach", "pearl", "pecan",
  "pedal", "penal", "perch", "peril", "perky", "petal", "petty", "picky", "piety", "pinch",
  "pious", "pixel", "pizza", "plaid", "plead", "pleat", "pluck", "plumb", "plume", "plump",
  "plush", "poach", "polar", "polka", "porch", "posse", "pouch", "preen", "prick", "prism",
  "privy", "probe", "prone", "prong", "prose", "proxy", "prune", "psalm", "pudgy", "puffy",
  "pulpy", "pulse", "punch", "pupil", "puppy", "puree", "purge", "purse", "pushy", "quack",
  "quail", "qualm", "quark", "quart", "quash", "quasi", "quell", "query", "quill", "quilt",
  "quirk", "quota", "rabid", "radar", "raspy", "raven", "rebel", "rebut", "recap", "recur",
  "regal", "rehab", "reign", "relax", "relay", "relic", "remit", "renal", "renew", "repay",
  "repel", "reply", "retro", "rhino", "rhyme", "ridge", "rifle", "rinse", "ripen", "riser",
  "risky", "rivet", "roach", "roast", "robot", "rodeo", "rogue", "roost", "rowdy", "ruddy",
  "ruler", "rumor", "runny", "rusty", "saber", "sadly", "salad", "salsa", "salty", "salve",
  "sandy", "sappy", "satin", "sauce", "saucy", "sauna", "savor", "savvy", "scald", "scalp",
  "scaly", "scamp", "scant", "scare", "scarf", "scary", "scoff", "scold", "scone", "scoop",
  "scoot", "scorn", "scour", "scout", "scowl", "scram", "scrap", "scrub", "scuba", "scuff",
  "seedy", "seize", "serum", "shack", "shade", "shady", "shake", "shaky", "shale", "shame",
  "shank", "shawl", "shear", "sheen", "sheep", "sheer", "shine", "shiny", "shire", "shoal",
  "shone", "shore", "shorn", "shout", "shove", "showy", "shred", "shrew", "shrub", "shrug",
  "shuck", "shunt", "shush", "siege", "sieve", "silky", "silly", "sinew", "singe", "siren",
  "sissy", "skate", "skiff", "skimp", "skirt", "skulk", "skull", "skunk", "slack", "slain",
  "slang", "slant", "slash", "slate", "sleek", "sleet", "slept", "slick", "slime", "slimy",
  "sling", "slink", "slope", "slosh", "sloth", "slump", "slung", "slunk", "slurp", "slush",
  "smack", "smash", "smear", "smell", "smelt", "smirk", "smock", "smote", "snack", "snail",
  "snake", "snaky", "snare", "snarl", "sneak", "sneer", "snide", "sniff", "snipe", "snoop",
  "snore", "snort", "snout", "snowy", "snuck", "snuff", "soapy", "sober", "soggy", "solar",
  "sonic", "sooty", "spade", "spank", "spasm", "spawn", "spear", "speck", "spell", "sperm",
  "spice", "spicy", "spike", "spiky", "spine", "spiny", "spire", "spite", "splat", "splay",
  "spoil", "spoof", "spool", "spoon", "spore", "spout", "spray", "spree", "sprig", "spunk",
  "spurn", "spurt", "squad", "squat", "stack", "stain", "stair", "stalk", "stall", "stamp",
  "stank", "stare", "stash", "stave", "stead", "steed", "steep", "steer", "stein", "stern", "stiff",
  "sting", "stink", "stint", "stoic", "stoke", "stole", "stomp", "stony", "stool", "stoop",
  "stork", "stout", "stove", "strap", "straw", "stray", "strut", "stump", "stung", "stunk",
  "stunt", "suave", "sulky", "sunny", "surly", "swamp", "swarm", "swath", "swear", "sweat",
  "swell", "swept", "swift", "swill", "swine", "swing", "swirl", "swish", "swoon", "swoop",
  "sword", "swore", "sworn", "swung", "tabby", "taboo", "tacit", "tacky", "taffy", "taint",
  "tally", "talon", "tamer", "tango", "tangy", "taper", "tardy", "tarot", "tasty", "taunt",
  "taupe", "tawny", "tease", "teddy", "tempo", "tempt", "tenet", "tenor", "tense", "tepid",
  "terse", "testy", "theta", "thigh", "thong", "thorn", "thump", "thyme", "tiara", "tidal",
  "tiger", "timer", "tipsy", "titan", "tithe", "toast", "token", "tonal", "tonic", "torch",
  "torso", "totem", "toxic", "trace", "tract", "trail", "tramp", "trash", "trawl", "tread",
  "triad", "trill", "tripe", "trite", "troll", "troop", "trope", "trout", "trove", "truce",
  "trump", "trunk", "tubby", "tulip", "tumor", "tunic", "turbo", "tutor", "twang", "tweak",
  "tweed", "tweet", "twirl", "twist", "ulcer", "ultra", "uncle", "uncut", "unfit", "unify",
  "unlit", "unmet", "unset", "untie", "unwed", "unzip", "upend", "usher", "usurp", "utter",
  "vague", "valet", "valor", "valve", "vapor", "vault", "vaunt", "vegan", "venom", "venue",
  "verge", "verse", "vicar", "vigil", "vigor", "villa", "viola", "viper", "viral", "visor",
  "vista", "vivid", "vixen", "vocal", "vodka", "vogue", "vowel", "vying", "wacky", "wafer",
  "wager", "wagon", "waist", "waltz", "waver", "waxen", "weary", "weave", "wedge", "weigh",
  "weird", "whack", "whale", "wharf", "wheat", "whelp", "whiff", "whine", "whiny", "whirl",
  "whisk", "whoop", "widen", "wider", "widow", "width", "wield", "wimpy", "wince", "winch",
  "windy", "wiser", "witch", "witty", "woken", "woozy", "wordy", "wrath", "wreak", "wreck",
  "wrest", "wring", "wrist", "wrung", "wryly", "yacht", "yearn", "yeast", "yield", "yodel",
  "yummy", "zebra", "zesty"
];

const STARWORD = { answers: STARWORD_ANSWERS, allowed: STARWORD_ALLOWED };

/* Exponer al navegador sin usar módulos. */
if (typeof window !== "undefined") window.STARWORD = STARWORD;
